### ISSUE TITLE
Collector seems to think that twine 1.1.1 is newer than twine 1.9.1

### ISSUE THREAD

**Issue by alexwlchan** [dependencies-io/collector-python-pip#14]
I have the following config in my `dependencies.yml`:

```yml
collectors:

  - type: python-pip
    path: twine/requirements.in
    actors:
      - type: python-pip
        dependencies: ".*"
```

This lead to a PR being opened on my repo where the collector decided to replace twine 1.9.1 with twine 1.1.1, which is a downgrade: https://github.com/alexwlchan/dockerfiles/pull/5

**Comment by davegaeddert** [comment]
Hey @alexwlchan, thanks for reporting. I think the issue is actually that you didn't specify `versions`  on the actor. Can you try adding a line?

```yaml
collectors:

  - type: python-pip
    path: twine/requirements.in
    actors:
      - type: python-pip
        dependencies: ".*"
        versions: "Y.Y.Y"  # major, minor, and patch updates
```

That would tell it to specifically sort using semantic versioning, and give you major, minor, and patch updates. Without a `versions` or `versions_regex` setting, I think the default behavior is just to pick off the top version from whatever order they came in as -- which unfortunately for pypi must just be alphabetically: https://pypi.python.org/pypi/twine/json

Let me know if that works.  More on version filtering here: https://www.dependencies.io/docs/dependencies-yml/version-filtering/
